
### **Assignment** **2**
##### Name :Priya Rajkumnar Jadhav
##### Class :TY-B
##### Batch :B
##### Roll No: 23107098

Title :Implement a basic AI prototype using TensorFlow/PyTorch for an application and Train the
model with relevant datasets and evaluate its performance.

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [ ]:
df=pd.read_csv('plant_disease_dataset.csv')

In [ ]:
df

      temperature   humidity   rainfall   soil_pH  disease_present
0       27.483571  33.215053   0.572758  4.975875                1
1       24.308678  36.945005  42.522346  8.165266                0
2       28.238443  34.026189  16.095303  6.316734                1
3       32.615149  41.104180  20.311015  6.164949                0
4       23.829233  51.971785  11.851323  8.482468                0
...           ...        ...        ...       ...              ...
9995    31.505510  81.939137  22.406822  5.862952                1
9996    15.008275  86.886833  10.503881  4.070539                0
9997    21.473416  81.891770  13.426869  7.101583                0
9998    27.478828  88.567649   9.719659  7.732620                0
9999    28.221942  71.900401   4.886391  4.383536                0

[10000 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   temperature      10000 non-null  float64
 1   humidity         10000 non-null  float64
 2   rainfall         10000 non-null  float64
 3   soil_pH          10000 non-null  float64
 4   disease_present  10000 non-null  int64
dtypes: float64(4), int64(1)
memory usage: 390.8 KB

In [ ]:
df.describe()

        temperature      humidity      rainfall       soil_pH  disease_present
count  10000.000000  10000.000000  10000.000000  10000.000000     10000.000000
mean      25.612191     62.119300      9.807522      6.245855         0.241000
std        5.813841     22.679977      9.852130      1.302465         0.427712
min        5.387999      6.244209      0.000055      4.000075         0.000000
25%       21.815610     40.772925      2.812822      5.122970         0.000000
50%       25.293238     72.211752      6.864898      6.232188         0.000000
75%       28.916048     81.032999     13.442871      7.386377         0.000000
max       56.686495    102.395421     84.654161      8.499875         1.000000

In [ ]:
df.isnull().sum()

temperature        0
humidity           0
rainfall           0
soil_pH            0
disease_present    0
dtype: int64

In [ ]:
x=df.drop(['disease_present'],axis=1)
y=df['disease_present']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
model = Sequential()

model.add(Dense(16, activation='relu', input_shape=(4,)))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
history = model.fit(
    x_train,
    y_train,
    epochs=20,
    batch_size=4,
    validation_split=0.2,
    verbose=1
)

Epoch 1/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8255 - loss: 0.4392 - val_accuracy: 0.8112 - val_loss: 0.4583
Epoch 2/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8344 - loss: 0.4209 - val_accuracy: 0.8138 - val_loss: 0.4560
Epoch 3/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8371 - loss: 0.4168 - val_accuracy: 0.8100 - val_loss: 0.4560
Epoch 4/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8309 - loss: 0.4236 - val_accuracy: 0.8125 - val_loss: 0.4539
Epoch 5/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8384 - loss: 0.4136 - val_accuracy: 0.8181 - val_loss: 0.4516
Epoch 6/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8347 - loss: 0.4118 - val_accuracy: 0.8144 - val_loss: 0.4503
Epoch 7/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8391 - loss: 0.4133 - val_accuracy: 0.8069 - val_loss: 0.4551
Epoch 8/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8427 - loss: 0.4060 - val_accuracy: 0.8163 - val_loss: 0.4514
Epoch 9/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8329 - loss: 0.4128 - val_accuracy: 0.8213 - val_loss: 0.4473
Epoch 10/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8406 - loss: 0.4035 - val_accuracy: 0.8138 - val_loss: 0.4525
Epoch 11/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8481 - loss: 0.3969 - val_accuracy: 0.8181 - val_loss: 0.4464
Epoch 12/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8404 - loss: 0.4014 - val_accuracy: 0.8200 - val_loss: 0.4469
Epoch 13/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8406 - loss: 0.4139 - val_accuracy: 0.8225 - val_loss: 0.4485
Epoch 14/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8352 - loss: 0.4164 - val_accuracy: 0.8169 - val_loss: 0.4515
Epoch 15/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8413 - loss: 0.4011 - val_accuracy: 0.8175 - val_loss: 0.4529
Epoch 16/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8380 - loss: 0.4077 - val_accuracy: 0.8206 - val_loss: 0.4477
Epoch 17/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8431 - loss: 0.4027 - val_accuracy: 0.8169 - val_loss: 0.4586
Epoch 18/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8410 - loss: 0.4005 - val_accuracy: 0.8219 - val_loss: 0.4478
Epoch 19/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8399 - loss: 0.4055 - val_accuracy: 0.8194 - val_loss: 0.4498
Epoch 20/20
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8358 - loss: 0.4111 - val_accuracy: 0.8238 - val_loss: 0.4442

In [ ]:
loss, accuracy = model.evaluate(x_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8425 - loss: 0.4076
Test Loss: 0.4215345084667206
Test Accuracy: 0.8335000276565552

In [ ]:
y_pred = (model.predict(x_test) > 0.5).astype("int32")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.8335
Precision: 0.7542662116040956
Recall: 0.45850622406639
F1 Score: 0.5703225806451613
Confusion Matrix:
 [[1446   72]
 [ 261  221]]